services:
  proxy:
    image: nginx:1.27-alpine
    volumes:
      - ./config/proxy.conf:/etc/nginx/conf.d/default.conf
      - ./example.llc.client.crt:/etc/nginx/conf.d/example.llc.client.crt
      - ./example.llc.client.key:/etc/nginx/conf.d/example.llc.client.key
      - ./Root.CA.example.llc.pem:/etc/nginx/conf.d/Root.CA.example.llc.pem
      - ./logs/proxy:/var/log/nginx
    ports:
      - "9001:80"
    links:
      - web
  web:
    image: nginx:1.27-alpine
    volumes:
      - ./config/web.conf:/etc/nginx/conf.d/default.conf
      - ./example.llc.server.crt:/etc/nginx/conf.d/example.llc.server.crt
      - ./example.llc.server.key:/etc/nginx/conf.d/example.llc.server.key
      - ./Root.CA.example.llc.pem:/etc/nginx/conf.d/Root.CA.example.llc.pem
      - ./logs/web:/var/log/nginx
      - ./www:/var/www
